TARGET          ?= stm32f303vc

LIBNAME         ?= opencm3_stm32f3
DEFS            ?= -DSTM32F3
DEFS            += -DSTD_CON=USART1
DEFS            += -DMST_SIZE=0x400

FP_FLAGS        ?= -mfloat-abi=hard -mfpu=fpv4-sp-d16
ARCH_FLAGS      ?= -mthumb -mcpu=cortex-m4 $(FP_FLAGS) 

OOCD            ?= openocd
OOCD_INTERFACE  ?= stlink-v2-1
OOCD_BOARD      ?= st_nucleo_f4

objs            += board_setup.o
objs            += stubs.o stm32_con.o
# aobjs           += helloworld.o
